### PR TITLE
LPS-182570 Fix MarketPlace routes

### PR DESCRIPTION
**Pull request by igor-franca**
Related tickets
[LPS-182570](https://issues.liferay.com/browse/LPS-182570)
[LPS-182551](https://issues.liferay.com/browse/LPS-182551)

### CODE REVIEW

**Comment by naraandrade** [comment]
Just started reviewing :)

**Review by naraandrade — CHANGES_REQUESTED** [review]
@igor-franca The "Add Apps" button on the Customer Dashboard should not be redirected to the "Create New App" flow, it should go to the Marketplace page so the user can purchase new apps.

**Comment by igor-franca** [comment]
> @igor-franca The "Add Apps" button on the Customer Dashboard should not be redirected to the "Create New App" flow, it should go to the Marketplace page so the user can purchase new apps.

Done! apologies for the delay.

**Comment by igor-franca** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
Just started reviewing :)

**Comment by naraandrade** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/134094

**Comment by naraandrade** [comment]
ci:close

**Pull request closed without merging**
