### PR TITLE
LPS-182548 Fix App Details Page calling

### PR DESCRIPTION
**Pull request by igor-franca**
Related [Ticket](https://issues.liferay.com/browse/LPS-182548)

### CODE REVIEW

**Comment by igor-franca** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
Just started reviewing :)

**Comment by naraandrade** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/134015

**Comment by naraandrade** [comment]
ci:close

**Pull request closed without merging**
