### PR TITLE
LPS-182257 Add Gate Modal and Customer Gate Page

### PR DESCRIPTION
**Pull request by igor-franca**
Realted Tickets:

https://issues.liferay.com/browse/LPS-181628
https://issues.liferay.com/browse/LPS-181398
https://issues.liferay.com/browse/LPS-181506
https://issues.liferay.com/browse/LPS-182257

### CODE REVIEW

**Comment by igor-franca** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
Just started reviewing :)

**Comment by naraandrade** [comment]
Solved conflicts here: https://github.com/naraandrade/liferay-portal/pull/216

**Comment by naraandrade** [comment]
ci:close

**Pull request closed without merging**
