### PR TITLE
LPS-181628

### PR DESCRIPTION
**Pull request by igor-franca**
[Related Ticket](https://issues.liferay.com/secure/RapidBoard.jspa?rapidView=7465)

### CODE REVIEW

**Comment by igor-franca** [comment]
ci:test:sf

**Comment by igor-franca** [comment]
ci:test:sf

**Comment by igor-franca** [comment]
ci:test:sf

**Comment by igor-franca** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
Just started reviewing :)

**Comment by naraandrade** [comment]
Resent here: https://github.com/naraandrade/liferay-portal/pull/207

**Comment by igor-franca** [comment]
ci:test:sf

**Pull request closed without merging**
